[package]
name = "regen-macro-impl"
version.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full", "extra-traits"] }

[dev-dependencies]
prettyplease = "0.2.35"
